### Pandas介紹
pandas在資料處理上的非常強大，且Pandas也和Matplotlib是一個基於Numpy的函式庫，而Padas也有另一種說法是，Pandas就是把excell的功能搬過來pyhton，許多在excell可以做到的事情，利用Pandas在python也可以辦到，如csv檔的讀取、刪減、增加、欄位的替換等等，這些功能在我們往後的案例都會常常使用到！

### Pandas相關程式介紹

In [1]:
# 導入函式庫
import pandas as pd
import numpy as np

### Series
Series是一種類似序列的指令，當在使用Series儲存資料的時候，會自動幫儲存的資料標上索引值(index)，所以可以利索引值去提取裡面的資料(儲存的資料類型不限)。

In [2]:
# 建立Series
S = pd.Series([1,2,3,'John',4,5])
S

0       1
1       2
2       3
3    John
4       4
5       5
dtype: object

In [3]:
# 提取裡面的資料和索引值：
values = S.values #提取資料
index = S.index #提取index
print(values)
print(index)

[1 2 3 'John' 4 5]
RangeIndex(start=0, stop=6, step=1)


In [4]:
# 自己定義喜歡的index並取出其中的index資料：
S2 = pd.Series([1,2,3,4,'John'], index=['Q','W','E','R','T'])#1.資料2.索引值
print(S2)
S2['T']

Q       1
W       2
E       3
R       4
T    John
dtype: object


'John'

### DataFrame
DataFrame是一種二維空間上的指令，就像是excel的表格一樣，有行和有列，DataFrame有索引值(index)和行數(column)，可以利用索引值和行數去抓到裡面的資料(儲存的資料類型不限)。

In [5]:
# 1. 建立DataFrame：

D = pd.DataFrame(np.arange(20).reshape((5,4)))
#np.arange從0列到19；reshape是把它變成5*4的型狀
print(D)

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19


In [6]:
# 2. 從diction轉換成dataframe：

data = {'區域': ['北區', '中區','南區','東區'],
        '人口': [300000, 500000, 412000, 240000],
        '地價(每坪)': [300000, 250000, 400000, 230000],
        '福利指數(滿分10)':[7,6,8,7]} #字典

D2 = pd.DataFrame(data) #轉換成dataframe格式
print(D2)
D2

   區域      人口  地價(每坪)  福利指數(滿分10)
0  北區  300000  300000           7
1  中區  500000  250000           6
2  南區  412000  400000           8
3  東區  240000  230000           7


區域      人口  地價(每坪)  福利指數(滿分10)
0  北區  300000  300000           7
1  中區  500000  250000           6
2  南區  412000  400000           8
3  東區  240000  230000           7

In [7]:
# 3.特定行查看：

print(D2['區域']) #中括號和行名稱

0    北區
1    中區
2    南區
3    東區
Name: 區域, dtype: object


In [8]:
# 4.特定列查看：

print(D2.loc[[0, 1]]) #查看0和1兩列

   區域      人口  地價(每坪)  福利指數(滿分10)
0  北區  300000  300000           7
1  中區  500000  250000           6


In [9]:
# 5.找特定位置：

print(D2.iloc[3,2])#用iloc函式指定第三列、第二行資料(是從0開始數唷)

230000


In [10]:
# 6.新增行數(column)
data = {'區域': ['北區', '中區','南區','東區'],
        '人口': [300000, 500000, 412000, 240000],
        '地價(每坪)': [300000, 250000, 400000, 230000],
        '福利指數(滿分10)':[7,6,8,7]} #字典
D3 = pd.DataFrame(data,columns=['區域','人口', '地價(每坪)', '福利指數(滿分10)','就業機會'])
D3

區域      人口  地價(每坪)  福利指數(滿分10) 就業機會
0  北區  300000  300000           7  NaN
1  中區  500000  250000           6  NaN
2  南區  412000  400000           8  NaN
3  東區  240000  230000           7  NaN

In [11]:
# 7.新增行資料：
D3['就業機會']=['高','中','高','中']
D3

區域      人口  地價(每坪)  福利指數(滿分10) 就業機會
0  北區  300000  300000           7    高
1  中區  500000  250000           6    中
2  南區  412000  400000           8    高
3  東區  240000  230000           7    中

In [12]:
# 8.刪除某欄：
D3.drop(columns=['就業機會', '地價(每坪)']) #刪除欄
D3.drop(index=[0, 1]) #刪除列

區域      人口  地價(每坪)  福利指數(滿分10) 就業機會
2  南區  412000  400000           8    高
3  東區  240000  230000           7    中

In [13]:
# 9.新增列及前面部分綜合(以防數據錯亂搞混)：

data = {'區域': ['北區', '中區','南區','東區'],
        '人口': [300000, 500000, 412000, 240000],
        '地價(每坪)': [300000, 250000, 400000, 230000],
        '福利指數(滿分10)':[7,6,8,7]} #字典
D3 = pd.DataFrame(data,columns=['區域','人口','地價(每坪)',"福利指數(滿分10)","就業機會"]) # 新增"就業機會"這欄
D3['就業機會']=['高','中','高','中'] #填入就業機會資料

D3 = D3.append({"區域":'西區', "人口":350000,"地價(每坪)": 280000 ,"福利指數(滿分10)":7 ,"就業機會":'低'},ignore_index=True) 
#1.要新增的字典2.預設是False，意思是一定要填入資料，所以要改成True
D3

區域      人口  地價(每坪)  福利指數(滿分10) 就業機會
0  北區  300000  300000           7    高
1  中區  500000  250000           6    中
2  南區  412000  400000           8    高
3  東區  240000  230000           7    中
4  西區  350000  280000           7    低

### Pandas應用於CSV檔
### 介紹CSV檔案
CSV全名是Comma-Separated Values，中文直接翻譯是逗號分隔值，也有人稱作字元分隔值(因為字元分隔不是用逗號)，而檔案是以純文字形式去儲存表個資料，也就是純文字檔，通常是由Excel轉出的資料檔。

In [14]:
# 讀取CSV檔
import pandas as pd #匯入函式庫
df_train = pd.read_csv('homedata.csv')#讀取csv檔，引號內是檔案路徑
print(df_train)

   id   price  sq_ft  floors  bedrooms  sale_month
0   1  380000   1900       2         4           8
1   2  350000   3380       1         4           9
2   3  254000   2070       2         3           1
3   4  230000   1150       1         3           2
4   5  540000   2040       1         3           6
5   6  240000   1550       1         3           5
6   7  158000   1520       2         3           4
7   8  200000    790       1         2          11
8   9  275000   1900       1         3          12
9  10  593500   4300       2         5          10


In [15]:
# 刪除不要的行
# 那我們在查看資料後，覺得售出月份對於定價影響不大，所以想要剃除，方法有兩個
# 1.正面進攻(比較簡單快速)：

df_train = df_train.drop("sale_month",axis=1)
#1.指定要的行或列名稱2.axis 0是指列(橫向)；1則是行(縱向) 
df_train

id   price  sq_ft  floors  bedrooms
0   1  380000   1900       2         4
1   2  350000   3380       1         4
2   3  254000   2070       2         3
3   4  230000   1150       1         3
4   5  540000   2040       1         3
5   6  240000   1550       1         3
6   7  158000   1520       2         3
7   8  200000    790       1         2
8   9  275000   1900       1         3
9  10  593500   4300       2         5

In [16]:
# 2.反面進攻(比較麻煩，保留特定行數)：

df_train = df_train.iloc[:,:5] 
#中括號內，第一個:前後都不田表示"列"全部都要保留；行則是保留0~4
#利用.iloc把index 5的移除(保留0~4)
#又因為冒號後面填n的話，會數到n-1，我們要保留0~4，所以，要填5
df_train

id   price  sq_ft  floors  bedrooms
0   1  380000   1900       2         4
1   2  350000   3380       1         4
2   3  254000   2070       2         3
3   4  230000   1150       1         3
4   5  540000   2040       1         3
5   6  240000   1550       1         3
6   7  158000   1520       2         3
7   8  200000    790       1         2
8   9  275000   1900       1         3
9  10  593500   4300       2         5

In [17]:
# 提取數值建立dataset
# 這邊要特地將表格內的數值取出，也就是我不要index和欄位，只要裡面的數值資料。

train_dataset = df_train.values #提取資料
print(train_dataset)
print('*'*30)
train_targets = train_dataset[:,1] #抓出price
print(train_targets)

[[     1 380000   1900      2      4]
 [     2 350000   3380      1      4]
 [     3 254000   2070      2      3]
 [     4 230000   1150      1      3]
 [     5 540000   2040      1      3]
 [     6 240000   1550      1      3]
 [     7 158000   1520      2      3]
 [     8 200000    790      1      2]
 [     9 275000   1900      1      3]
 [    10 593500   4300      2      5]]
******************************
[380000 350000 254000 230000 540000 240000 158000 200000 275000 593500]
