### Tensorflow介紹
TensorFlow 是一種採用數據流圖(Dataflow Graph)並用於數值計算的開源函式庫，更是一個用於開發機器學習的平台，而且同樣的程式碼可以用CPU執行也可以用GPU執行，並支援許多語言：pyhton、C++、Java、Go...。更簡單的直接一句話概括是，Tensorflow就是Google開發出來的開源機器學習工具

### 那為什麼叫Tensorflow呢？
先介紹下Tensorflow會用到的數據流圖(Dataflow Graph)，是指Tensorflow會依照數據流圖來根據各操作間的關係來表示計算。概念大概是：
* 定義數據流圖(Dataflow Graph)
* 建立Tensorflow會話(Session)，並運行數據流圖

數據流圖(Dataflow Graph)樣子(利用Tensorboard建立的視覺化，之後會提到)：

![圖](DataflowGraph.png)


### 那名字的由來：
* Tensor的中文是張量的意思，而張量是「陣列」的廣義說法，所以Tensor可以代表是一維陣列、二維陣列...N維陣列。
* Flow的中文是流的意思，類似一種流程的想法，就像我們寫程式，宣告變數，傳遞變數，計算，再傳遞...等等，最後輸出，也有流的想法在。然而，Tensorflow的流和上述不太相同，Tensorflow是把所有的節點設好，才用一個叫**sess.run()**來啟動計算圖。

In [1]:
import tensorflow as tf #引入函式庫
x = tf.constant(2)      #constant是指不可改變的數字(也就是常數)

#常用語法tf.constant(value,dtype=None,shape=None) 分別是 1.數值 2.型態 3.形狀(幾維)
y = tf.constant(3) 
z = tf.add(x,y) #兩常數相加

with tf.Session() as sess : #幫tf.Session()取個綽號
#且用 with as 當程式結束後會 釋放資源
    print(sess.run(z)) #啟動數據流圖

5


1.張量(tensor)：昨天有提到，就是N維陣列，可以想成是數據。
2.節點(op)：有運算操作的概念，當一個op獲得數個Tensor時，會執行計算可能產生一個或多個Tensor。
3.會話(session)：Tensorflow是基於數據流圖的學習框架，而Session就是圖和執行之間的媒介。

### Tensorboard
因為Tensorflow經常用於訓練「大規模深度神經網路」計算，往往太過複雜，為了能夠更清楚其中的奧秘，才會有了Tensorboard的發展，Tensorboard是用於視覺化數據流程、損失函式查看或者準確度變化的分析等等，用Tensorboard都可以輕易達成目的

In [2]:
import tensorflow as tf #引入函式庫

x = tf.constant([2],shape = [2,3],name = 'a') 

#2.shape其實很像reshape的概念，就是把它的形狀改變！
#3.name就是重新命名，讓它在視覺化時有個名分
y = tf.constant([3],shape = [2,3],name = 'b') 
z = tf.add(x,y)

write = tf.summary.FileWriter('./graphs',tf.get_default_graph())
#tf.summary.FileWriter生成一個空間讓指定的東西跑進去
#1.路徑(這樣的寫法會跑去程式檔的資料夾位置那)，graphs是名稱
#2.tf.get_default_graph()獲取當前默認的計算圖
with tf.Session() as sess : #命名；且文件關閉後釋放資源
    print(sess.run(z)) #啟動數據流圖

[[5 5 5]
 [5 5 5]]


### 常用的張量資料型態
* 常數(constant)：上篇有提到的，固定數值的張量。
* 變量(variable)：在tensorflow中，變量跟我們一般的程式變數不太一樣，尤其是只要有設定變量，一定要記得初始化，且要經過sess.run才能成功被激活。變量可透過運行操作來改變其中的張量。

In [3]:
import tensorflow as tf
a = tf.Variable(5,name = "a")
b = tf.Variable(17,name = "b")
c = a*b

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) 
    #全部變量初始化，沒這行會錯
    print(sess.run(c))

85


* 佔位符(placeholder)：是一種常量，但要在run內傳遞，不像constant直接給定數值，而是由外部傳來的data進行給值。

In [4]:
import tensorflow as tf
x = tf.placeholder(tf.float32,shape=[3]) #1.dtype:32位浮點數2.形狀3
y = tf.constant([5,5,5],tf.float32) 
z = x + y

with tf.Session() as sess:
    #print(sess.run(z)) #只有這樣會有bug，因為你還沒給placeholder數值，他只是佔了空間而已
    print(sess.run(z ,feed_dict ={x : [1,2,3]}) )

[6. 7. 8.]


### 常用的op介紹
Tensorflow支援的基本操作：
![圖](Tensorflow.png)

以上有許多簡單的運算其實可以不用打到tf.XXX，可以直接用python一般的程式碼去計算，如tf.add()和"+"就幾乎是一樣的，所以上述這些就不再多做說明。
我們會著重在以下比較特別，卻有機會會使用到的指令：

In [5]:
# 1.上面沒有的一些基礎的操作
import tensorflow as tf
x = tf.constant([-1,2],name = 'x',dtype = tf.float32)
y = tf.constant([[0,2],[2,3]],name = 'y',dtype = tf.float32)

with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))
    print('*'*40)
    print(sess.run(tf.square(x))) #平方
    print(sess.run(tf.abs(x))) #絕對值
    print('*'*40)
    print(sess.run(tf.exp(y))) #取e
    print(sess.run(tf.sqrt(y))) #開根號
    print('*'*40) 
    print(sess.run(tf.pow(y,3))) #幾次方的意思，這裡是3次方

[-1.  2.]
[[0. 2.]
 [2. 3.]]
****************************************
[1. 4.]
[1. 2.]
****************************************
[[ 1.        7.389056]
 [ 7.389056 20.085537]]
[[0.        1.4142134]
 [1.4142134 1.7320508]]
****************************************
[[ 0.  8.]
 [ 8. 27.]]


In [6]:
# 2.創建全部是0的張量：
# 語法：tf.zeros(shape, dtype=tf.float32, name=None)

import tensorflow as tf
a = tf.zeros(shape=[4, 5], dtype=tf.int32, name='a')#是4*5的矩陣
with tf.Session() as sess:
    print(sess.run(a))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [7]:
# 3.序列：
# (1)tf.lin_space：會平均計算，然後在間隔中產生數值
# 語法：tf.lin_space(start,stop,num,name=None)

import tensorflow as tf
a = tf.linspace(1.0, 5.0, 5) #1.起始值10 2.結束值13 3.數量是4
with tf.Session() as sess:
    print(sess.run(a))

[1. 2. 3. 4. 5.]


In [8]:
# (2)tf.range：建立數字序列
# 語法：tf.range(start, limit=None, delta=1, dtype=None,name='range')

import tensorflow as tf
a = tf.range(0,10,1) #1.從0開始 2.10以前 3.公差是1
b = tf.range(10) #10是限制
#因為(start=0, limit=None, delta=1, dtype=None, name='range')，所以起點0和公差1都有預設了
#所以a,b相同
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
# 4.隨機產生常量：
# 語法：tf.random_normal (shape, mean=0.0, stddev=1.0, dtype=tf.float32,seed=None, name=None)

import tensorflow as tf
a = tf.random_normal([3,4],10,2,tf.float64,1)
#1. 3*4矩陣2.平均是10 3.標準差是2 4. 64位浮點數 
#5.seed:是一個整數，設定後，每次生成的隨機數都一樣 
b = tf.random_normal([3,4],10,2,tf.float64,1)
c = tf.random_normal([3,4],10,2,tf.float64,2)
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b)) #會發現seed相同時，生出的隨機數都一樣
    print('*'*40)
    print(sess.run(c))

[[10.48565509  9.29400356  8.32698442  9.51286196]
 [13.82013658  9.26140554 10.72015467  6.56759923]
 [11.3093726   8.49358633 10.32934506  7.97655564]]
[[10.48565509  9.29400356  8.32698442  9.51286196]
 [13.82013658  9.26140554 10.72015467  6.56759923]
 [11.3093726   8.49358633 10.32934506  7.97655564]]
****************************************
[[ 7.40522701 10.13930217  9.16300271 10.90471891]
 [10.83600015  9.42317886  8.31473349 10.29167639]
 [ 9.93777917 13.99150225  9.07006875 10.04976989]]
