# Numpy函式庫

### 那到底什麼是Numpy？
NumPy是python的重要模組，主要用來資料處理，支援高階大量的矩陣、維度陣列運算。python在處理很大很多的資料時，其實，原本裡面的list效能並不是太好，而NumPy底層以C語言開發，具備平尋處理能力，相對起來處理會相當快速。
還有還有，NumPy函式庫與資料科學相關套件(也就是我們之後會大量使用到的分析工具，如Matplotlib)能互相配合，且能將神經網路轉為陣列進行處理！

### Numpy陣列
numpy重點在矩陣、陣列的操作，其中一個重要的特點就是對N維數組對象的ndarray進行操作。ndarray的常見屬性有型態、形狀及數值。

In [1]:
# 1. 一階陣列
import numpy as np
x = np.array([1,2,3,4,5])

print("Type is %s "%(type(x))) #型態
print("Shpae is %s "%(x.shape,)) #形狀
print("Values are %s"%(x)) #數值

Type is <class 'numpy.ndarray'> 
Shpae is (5,) 
Values are [1 2 3 4 5]


In [2]:
# 2. 二階陣列
y = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Type is %s "%(type(y))) #型態
print("Shpae is %s "%(y.shape,)) #形狀
print("Values are %s"%(y)) #數值

Type is <class 'numpy.ndarray'> 
Shpae is (2, 5) 
Values are [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### 廣播(Broadcast)
廣播(Broadcast)是numpy對不同形狀的數組計算的方式，會有自動推播的功能，直接來看例子會更容易明白。

In [3]:
# 會發現不同shape時，使用numpy直接相加會有推到最大形狀並且相加的功能。

import numpy as np 
 
a = np.array([[ 0, 0, 0],
           [1,1,1],
           [2,2,2],
           [3,3,3]])
b = np.array([1,2,3])
print(a + b)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [4]:
# 矩陣指標
# 類似list的索引值，可以從找索取numpy內的部分陣列。

import numpy as np 
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("Type is %s "%(type(a))) #型態
print("Shpae is %s "%(a.shape,)) #形狀
print("Values are %s"%(a)) #數值

print("*"*30)

b = a[:3,1:3]  #row取0,1,2列；column取1,2行
print("Type is %s "%(type(b))) #型態
print("Shpae is %s "%(b.shape,)) #形狀
print("Values are %s"%(b)) #數值

Type is <class 'numpy.ndarray'> 
Shpae is (4, 4) 
Values are [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
******************************
Type is <class 'numpy.ndarray'> 
Shpae is (3, 2) 
Values are [[ 2  3]
 [ 6  7]
 [10 11]]
